services:

  # ================================
  # BASE DE DATOS SQL SERVER
  # ================================
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sgd_sqlserver
    environment:
      MSSQL_SA_PASSWORD: "Admin1234!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - sgd_network

  # ================================
  # BASE DE DATOS POSTGRESQL
  # ================================
  postgres:
    image: postgres:16
    container_name: sgd_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin1234!
      POSTGRES_DB: sgd_reportes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sgd_network

  # ================================
  # BASE DE DATOS MONGODB
  # ================================
  mongodb:
    image: mongo:7
    container_name: sgd_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Admin1234!
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - sgd_network

  # ================================
  # MÓDULO PHP
  # ================================
  php-app:
    build:
      context: ../src/php-app
      dockerfile: Dockerfile
    container_name: sgd_php
    ports:
      - "8080:80"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: sgd_reportes
      DB_USER: admin
      DB_PASSWORD: Admin1234!
    depends_on:
      - postgres
    networks:
      - sgd_network

  # ================================
  # MÓDULO NODE.JS
  # ================================
  node-service:
    build:
      context: ../src/node-service
      dockerfile: Dockerfile
    container_name: sgd_node
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://admin:Admin1234!@mongodb:27017
      PORT: 3000
    depends_on:
      - mongodb
    networks:
      - sgd_network

  # ================================
  # MÓDULO .NET CORE
  # ================================
  dotnet-app:
    build:
      context: ../src/dotnet-core/SistemaGestion
      dockerfile: Dockerfile
    container_name: sgd_dotnet
    ports:
      - "5000:5000"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=sgd_principal;User Id=appuser;Password=App1234!;TrustServerCertificate=True;Encrypt=False;"
    depends_on:
      - sqlserver
    networks:
      - sgd_network

volumes:
  sqlserver_data:
  postgres_data:
  mongodb_data:

networks:
  sgd_network:
    driver: bridge